# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-30 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0003_auto_20180622_1759'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('product_base_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_base_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('package', models.CharField(blank=True, max_length=200, null=True)),
                ('pricing_tier', models.CharField(blank=True, max_length=200, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_category', models.CharField(blank=True, max_length=200, null=True)),
                ('hide_from_online_customers', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_user', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('tracking_id', models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModifier',
            fields=[
                ('modifier_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('modifier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_percent', models.FloatField(blank=True, null=True)),
                ('product_base_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dow', models.CharField(blank=True, max_length=200, null=True)),
                ('start_hour', models.IntegerField(blank=True, null=True)),
                ('start_min', models.IntegerField(blank=True, null=True)),
                ('end_hour', models.IntegerField(blank=True, null=True)),
                ('end_min', models.IntegerField(blank=True, null=True)),
                ('start_event_date', models.CharField(blank=True, max_length=200, null=True)),
                ('end_event_date', models.CharField(blank=True, max_length=200, null=True)),
                ('start_day_of_month', models.CharField(blank=True, max_length=200, null=True)),
                ('end_day_of_month', models.CharField(blank=True, max_length=200, null=True)),
                ('start_month', models.CharField(blank=True, max_length=200, null=True)),
                ('end_month', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_user', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('tracking_id', models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking')),
            ],
        ),
    ]
