# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_auto_20180808_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventallocation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventtier',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
