# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0009_eventcentertier'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpromo',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventpromo',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpromo',
            name='eventByDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpromo',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
