# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_eventpricebycenter_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventallocation',
            old_name='row_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='eventallocation',
            old_name='category',
            new_name='subGroup',
        ),
        migrations.RenameField(
            model_name='eventallocation',
            old_name='sub_product',
            new_name='subProduct',
        ),
        migrations.RenameField(
            model_name='eventtier',
            old_name='row_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='eventtier',
            old_name='category',
            new_name='subGroup',
        ),
        migrations.RemoveField(
            model_name='eventallocation',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='eventtier',
            name='category_id',
        ),
    ]
