# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0013_leaguepricingsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguepricingsheet',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
