# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-27 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Centers', '0015_centers_arcade_type'),
        ('Audit', '0003_auto_20180622_1759'),
        ('Models', '0014_leaguepricingsheet_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(blank=True, max_length=200, null=True)),
                ('league_name', models.CharField(blank=True, max_length=500, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('lineage_cost', models.FloatField(blank=True, null=True)),
                ('centaman_league_number', models.CharField(blank=True, max_length=200, null=True)),
                ('dow', models.IntegerField(blank=True, null=True)),
                ('cover', models.IntegerField(blank=True, null=True)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_user', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('center_id', models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers')),
                ('tracking_id', models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking')),
            ],
        ),
    ]
