# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0016_rmps'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmps',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
