# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0017_rmps_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmps',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
