# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-28 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0020_auto_20190128_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeagueNew',
            new_name='League',
        ),
    ]
