# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-19 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0021_auto_20190128_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='last',
            field=models.BooleanField(default=False),
        ),
    ]
