# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0023_league_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='frequency',
            new_name='leagueFrequecy',
        ),
    ]
