# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-07 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0025_auto_20190228_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='RowCreatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='RowModifiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='rowHash',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
