# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-07 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0031_leaguealocohol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguealocohol',
            name='transactionNumber',
        ),
    ]
