# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-04 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_remove_foodmenutable_effective_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenutable',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
