# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Audit', '0002_tracking_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Centers', '0002_auto_20180321_1354'),
        ('Pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailshoepriceold',
            name='create_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='retailshoepriceold',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Period'),
        ),
        migrations.AddField(
            model_name='retailshoeprice',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='retailshoeprice',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers'),
        ),
        migrations.AddField(
            model_name='retailshoeprice',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Product'),
        ),
        migrations.AddField(
            model_name='retailshoeprice',
            name='schedule',
            field=models.ForeignKey(blank=True, db_column='schedule_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.ProductWeeklySchedule'),
        ),
        migrations.AddField(
            model_name='retailshoeprice',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
        migrations.AddField(
            model_name='retailbowlingpriceold',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers'),
        ),
        migrations.AddField(
            model_name='retailbowlingpriceold',
            name='create_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='retailbowlingpriceold',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Period'),
        ),
        migrations.AddField(
            model_name='retailbowlingprice',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='retailbowlingprice',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers'),
        ),
        migrations.AddField(
            model_name='retailbowlingprice',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Product'),
        ),
        migrations.AddField(
            model_name='retailbowlingprice',
            name='schedule',
            field=models.ForeignKey(blank=True, db_column='schedule_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.ProductWeeklySchedule'),
        ),
        migrations.AddField(
            model_name='retailbowlingprice',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
        migrations.AddField(
            model_name='productweeklyschedule',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='productweeklyschedule',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers'),
        ),
        migrations.AddField(
            model_name='productweeklyschedule',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Product'),
        ),
        migrations.AddField(
            model_name='productweeklyschedule',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='schedule',
            field=models.ForeignKey(blank=True, db_column='schedule_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.ProductWeeklySchedule'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
        migrations.AddField(
            model_name='product',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
        migrations.AddField(
            model_name='pricingtiertable',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='pricingtiertable',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
        migrations.AddField(
            model_name='period',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='period',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers'),
        ),
        migrations.AddField(
            model_name='period',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
    ]
