# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0005_productschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtiertable',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='center_type',
            field=models.CharField(blank=True, choices=[('traditional', 'traditional'), ('experiential', 'experiential'), ('session', 'session')], max_length=100, null=True),
        ),
    ]
