# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0008_pricingtiertable_center_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
