# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0009_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
