# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0010_productopt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productopt',
            old_name='date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='productopt',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
