# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-13 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0011_auto_20180513_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopt',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productopt',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
