# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0012_auto_20180513_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='perpetual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retailbowlingprice',
            name='perpetual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retailshoeprice',
            name='perpetual',
            field=models.BooleanField(default=True),
        ),
    ]
