# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-05 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0014_bundle_bundleproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtiertable',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
