# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0015_auto_20180705_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='always_opt_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
