# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodByCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodprice',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=30),
        ),
    ]
