# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Centers', '0005_auto_20180402_1313'),
        ('Pricing', '0003_productopt'),
        ('Audit', '0002_tracking_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BSChangeReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('price_old', models.FloatField(blank=True, null=True)),
                ('price_new', models.FloatField(blank=True, null=True)),
                ('opt', models.CharField(blank=True, choices=[('In', 'In'), ('Out', 'Out')], max_length=100, null=True)),
                ('center_id', models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Product')),
                ('tracking_id', models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
