# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSChangeReport', '0002_bschangereport_is_bulk_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bschangereport',
            name='is_bulk_change',
            field=models.BooleanField(),
        ),
    ]
