# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSChangeReport', '0003_auto_20180405_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bschangereport',
            name='is_bulk_change',
            field=models.BooleanField(default=False),
        ),
    ]
