# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-06 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSChangeReport', '0004_auto_20180405_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bschangereport',
            name='product_type',
        ),
    ]
