# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSChangeReport', '0005_remove_bschangereport_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bschangereport',
            name='email_notice',
            field=models.BooleanField(default=False),
        ),
    ]
