# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-07 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSChangeReport', '0007_bschangereport_product_rmps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bschangereport',
            name='product_RMPS',
        ),
    ]
