# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Food', '0001_initial'),
        ('Pricing', '0005_productschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Audit', '0002_tracking_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodChangeReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tier', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_old', models.FloatField(blank=True, null=True)),
                ('price_new', models.FloatField(blank=True, null=True)),
                ('menu_id', models.ForeignKey(blank=True, db_column='menu_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Food.Menu')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pricing.Product')),
                ('tracking_id', models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
