# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodChangeReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodchangereport',
            name='product_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodchangereport',
            name='product_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
