# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodChangeReport', '0002_auto_20180417_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodchangereport',
            name='email_notice',
            field=models.BooleanField(default=False),
        ),
    ]
