# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodByCenter', '0002_foodprice_status'),
        ('FoodChangeReport', '0003_foodchangereport_email_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodchangereport',
            name='menu_id_',
            field=models.ForeignKey(blank=True, db_column='menu_id_', null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodByCenter.Menu'),
        ),
    ]
