# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-29 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0016_centers_rvp'),
        ('FoodChangeReport', '0005_auto_20190429_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodchangereport',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers'),
        ),
    ]
