# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Audit', '0002_tracking_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhours',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='openhours',
            name='center_id',
            field=models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers'),
        ),
        migrations.AddField(
            model_name='openhours',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
        migrations.AddField(
            model_name='centers',
            name='action_user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='centers',
            name='tracking_id',
            field=models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking'),
        ),
    ]
