# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0006_auto_20180423_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centers',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
