# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0007_auto_20180531_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='noaa_weather_station_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
