# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0008_centers_noaa_weather_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='weather_sync',
            field=models.BooleanField(default=False),
        ),
    ]
