# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0010_auto_20180606_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='end_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='open_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
