# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-03 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0011_auto_20180614_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='bowling_event_tier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
