# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0012_centers_bowling_event_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='event_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centers',
            name='event_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
