# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0013_auto_20180725_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centers',
            old_name='event_district',
            new_name='sale_region',
        ),
        migrations.RenameField(
            model_name='centers',
            old_name='event_region',
            new_name='territory',
        ),
    ]
