# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centers', '0014_auto_20180725_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='arcade_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
