# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0004_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
