# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-07 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Centers', '0016_centers_rvp'),
        ('Audit', '0003_auto_20180622_1759'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChangeReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_RMPS', models.CharField(blank=True, max_length=100, null=True)),
                ('price_old', models.FloatField(blank=True, null=True)),
                ('price_new', models.FloatField(blank=True, null=True)),
                ('email_notice', models.BooleanField(default=False)),
                ('center_id', models.ForeignKey(blank=True, db_column='center_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Centers.Centers')),
                ('tracking_id', models.ForeignKey(blank=True, db_column='tracking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Audit.Tracking')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
